import { SessionProvider } from 'next-auth/react'
import Header from './components/Header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import { NextAuthProvider } from '~/app/providers/nextauth.provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <NextAuthProvider>
          <Header />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
